apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate
  namespace: {{.Values.namespace}}
spec:
  secretName: certificate-secret
  duration: 2160h
  renewBefore: 1h
  keySize: 4096
  dnsNames:
  - {{.Values.dnsname}}
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
