apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: internal
    generation: 1
    name: go-test-server-ingress
    namespace: {{.Values.namespace}}
  spec:
    rules:
    - host: {{.Values.dnsname}}
      https:
        paths:
        - backend:
            serviceName: {{ include "go-test-server.fullname" . }}
            servicePort: 8080
          path: /
    tls:
    - hosts:
      - {{.Values.dnsname}}
      secretName: certificate-secret
  status:
    loadBalancer:
      ingress:
      - {}
kind: List